### ISSUE TITLE
angel.psagent.cache.sync.timeinterval.ms

### ISSUE THREAD

**Issue by qmlmoon** [Angel-ML/angel#362]
1.5.0版本开始angel.psagent.cache.sync.timeinterval.ms默认值从200ms加到5s，请问是什么原因呢？这样在BSP条件下每次新一轮的getRow都需要clockCache等待几秒钟与PS同步。

**Comment by qmlmoon** [comment]
或者说我在1.5.1版本下将angel.psagent.cache.sync.timeinterval.ms设回200ms有什么tradeoff吗

**Comment by paynie** [comment]
The default parameters can only meet common scenarios. Because Angel is generally used to deal with large models with large partition numbers, too short synchronization time will result in more network communication, which has a certain impact on performance. Of course, if the model is small or if the iteration time is not long, you can reduce this parameter and it has no effect.
