### ISSUE TITLE
Does anyone compile the serving code successfully?and how can I generate a pmml of my model? thanks

### ISSUE THREAD

**Issue by mattxia** [Angel-ML/angel#718]
1.I can't compile the serving code successfully. Did anyone compile the code successfully?
2.And can Angel generate a PMML described model ,so that I can do this

**Comment by wangcaihua** [comment]
1) I am not sure the "Serving code" mean. there are an serving branch in Angel Project and a independent Serving project. which do you mean. 

The Serving project will release with Angel 3.0, so it is under release now. Since of its dependences are in Angel 3.0, it is resonable that you cannot complie Serving project successfully.

but if you want to try Serving project in advance, and can follow the instructions:

- pull the Angel project for Github
- switch to the Serving branch, which the a temp branch for Angel 3.0
- complie and install Angel to you local macen repository
- pull the Serving project from Github
- complie and install Seving

2) Angel cannot generate a PMML model, since PMML is not efficient in hold very big models. Angel have its own model format, which is suported by Serving.

**Comment by mattxia** [comment]
直接用中文吧，因为git里面有一个https://github.com/Angel-ML/serving的项目，所以以为serving的代码在这个里面，但是下下来编译不过...废老鼻子劲把Pmml的部分LR跑通了，以为angel支持Pmml.

好的，在这个branch里面找到了，先按照你的方法整下吧，多谢先

**Comment by mattxia** [comment]
已经OK了，多谢
